        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 07 15:50:11 2010
        MODULE JFUNC2BIS__genmod
          INTERFACE 
            SUBROUTINE JFUNC2BIS(K,L,T,JOUT)
              REAL(KIND=8), INTENT(IN) :: K
              REAL(KIND=8), INTENT(IN) :: L
              REAL(KIND=8), INTENT(IN) :: T
              REAL(KIND=8), INTENT(OUT) :: JOUT(2101)
            END SUBROUTINE JFUNC2BIS
          END INTERFACE 
        END MODULE JFUNC2BIS__genmod
